spring:
  security:
    oauth2:
      resourceserver:
        id: http://localhost:8080/movies
        jwk:
          jwk-set-uri: https://webflux.au.auth0.com/.well-known/jwks.json
          issuer-uri: https://webflux.au.auth0.com/